<?xml version="1.0"?>

<robot name="dual_arm" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find motoman_sia5d_support)/urdf/sia5d_macro.xacro"/>
  <xacro:motoman_sia5d prefix="left"/>
  <xacro:motoman_sia5d prefix="right" />

  <xacro:property name="base_length" value="1" />
  <xacro:property name="base_width" value="0.5" />
  <xacro:property name="base_height" value=".2" />
  <xacro:property name="adjust_arm" value=".2" />

  <material name="blue">
    <color rgba="0 0 .8 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>	

  <link name="base_box">
    <visual>
      <geometry>
	<box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <joint name="base_joint_left" type="fixed">
      <parent link="base_box"/>
      <child link="leftbase_link"/>
      <origin xyz="-${base_length/2-adjust_arm} 0 ${base_height}" />
  </joint>

  <joint name="base_joint_right" type="fixed">
      <parent link="base_box"/>
      <child link="rightbase_link"/>
      <origin xyz="${base_length/2-adjust_arm} 0 ${base_height}" />
  </joint>
  
</robot>
