controller_list:
  - name: fake_left_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
  - name: fake_right_controller
    joints:
      - rightshoulder_pan_joint
      - rightshoulder_lift_joint
      - rightelbow_joint
      - rightwrist_1_joint
      - rightwrist_2_joint
      - rightwrist_3_joint
  - name: fake_both_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
      - rightshoulder_pan_joint
      - rightshoulder_lift_joint
      - rightelbow_joint
      - rightwrist_1_joint
      - rightwrist_2_joint
      - rightwrist_3_joint