controller_list:
  - name: fake_left_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
  - name: fake_right_controller
    joints:
      - rightjoint_s
      - rightjoint_l
      - rightjoint_e
      - rightjoint_u
      - rightjoint_r
      - rightjoint_b
      - rightjoint_t
  - name: fake_both_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
      - rightjoint_s
      - rightjoint_l
      - rightjoint_e
      - rightjoint_u
      - rightjoint_r
      - rightjoint_b
      - rightjoint_t