# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from griffin_powermate/PowermateEvent.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PowermateEvent(genpy.Message):
  _md5sum = "7c609a1e7695a65cfaa2fdba1e74ac79"
  _type = "griffin_powermate/PowermateEvent"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Dirction values can be -1 for counter-clockwise, 0 for no, and 1 clockwise rotation
int8 direction

# Sum of direction values since the launch of the node
int64 integral

# TRUE while button is pressed, FALSE otherwise
bool is_pressed

# TRUE if the event was triggered by a push or a release of the button; FALSE otherwise
bool push_state_changed"""
  __slots__ = ['direction','integral','is_pressed','push_state_changed']
  _slot_types = ['int8','int64','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       direction,integral,is_pressed,push_state_changed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PowermateEvent, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.direction is None:
        self.direction = 0
      if self.integral is None:
        self.integral = 0
      if self.is_pressed is None:
        self.is_pressed = False
      if self.push_state_changed is None:
        self.push_state_changed = False
    else:
      self.direction = 0
      self.integral = 0
      self.is_pressed = False
      self.push_state_changed = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_bq2B.pack(_x.direction, _x.integral, _x.is_pressed, _x.push_state_changed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.direction, _x.integral, _x.is_pressed, _x.push_state_changed,) = _struct_bq2B.unpack(str[start:end])
      self.is_pressed = bool(self.is_pressed)
      self.push_state_changed = bool(self.push_state_changed)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_bq2B.pack(_x.direction, _x.integral, _x.is_pressed, _x.push_state_changed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.direction, _x.integral, _x.is_pressed, _x.push_state_changed,) = _struct_bq2B.unpack(str[start:end])
      self.is_pressed = bool(self.is_pressed)
      self.push_state_changed = bool(self.push_state_changed)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_bq2B = struct.Struct("<bq2B")
